# Site settings
title: Finite Heap
email: root@finiteheap.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about computer stuff mostly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://finiteheap.com" # the base hostname & protocol for your site
github_username:  mkvenkatesh
exclude: [deploy]

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# pagination
paginate: 5